// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv548VSuWFqcs-5wi43_dy-scpJ0VDFNE',
    appId: '1:576263923687:web:9e16aabfa7a4ba945bbf42',
    messagingSenderId: '576263923687',
    projectId: 'klik-4e0ed',
    authDomain: 'klik-4e0ed.firebaseapp.com',
    storageBucket: 'klik-4e0ed.firebasestorage.app',
    measurementId: 'G-TK42Z7GWJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNyNKjNiBMWxaUpTu5F9VeNNtYed7Gco',
    appId: '1:576263923687:android:b127215912af53e35bbf42',
    messagingSenderId: '576263923687',
    projectId: 'klik-4e0ed',
    storageBucket: 'klik-4e0ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsnQPbI0mWAJife_4PoR-Rm96-V-zbXY4',
    appId: '1:576263923687:ios:8523f466adabb3a95bbf42',
    messagingSenderId: '576263923687',
    projectId: 'klik-4e0ed',
    storageBucket: 'klik-4e0ed.firebasestorage.app',
    androidClientId: '576263923687-16hv9qndo5u9n0o2vq777id7k96u6a06.apps.googleusercontent.com',
    iosClientId: '576263923687-p2qv9mutefhg9a37tch5413fjvoslnhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.klikq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsnQPbI0mWAJife_4PoR-Rm96-V-zbXY4',
    appId: '1:576263923687:ios:8523f466adabb3a95bbf42',
    messagingSenderId: '576263923687',
    projectId: 'klik-4e0ed',
    storageBucket: 'klik-4e0ed.firebasestorage.app',
    androidClientId: '576263923687-16hv9qndo5u9n0o2vq777id7k96u6a06.apps.googleusercontent.com',
    iosClientId: '576263923687-p2qv9mutefhg9a37tch5413fjvoslnhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.klikq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv548VSuWFqcs-5wi43_dy-scpJ0VDFNE',
    appId: '1:576263923687:web:4415b0b92976972e5bbf42',
    messagingSenderId: '576263923687',
    projectId: 'klik-4e0ed',
    authDomain: 'klik-4e0ed.firebaseapp.com',
    storageBucket: 'klik-4e0ed.firebasestorage.app',
    measurementId: 'G-D3EQE1N0CL',
  );

}